/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MenuItemType } from './MenuItemType';
import {
    MenuItemTypeFromJSON,
    MenuItemTypeFromJSONTyped,
    MenuItemTypeToJSON,
    MenuItemTypeToJSONTyped,
} from './MenuItemType';

/**
 * 
 * @export
 * @interface MenuItem
 */
export interface MenuItem {
    /**
     * 
     * @type {string}
     * @memberof MenuItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof MenuItem
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof MenuItem
     */
    id?: number | null;
    /**
     * 
     * @type {MenuItemType}
     * @memberof MenuItem
     */
    type?: MenuItemType;
}



/**
 * Check if a given object implements the MenuItem interface.
 */
export function instanceOfMenuItem(value: object): value is MenuItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function MenuItemFromJSON(json: any): MenuItem {
    return MenuItemFromJSONTyped(json, false);
}

export function MenuItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : MenuItemTypeFromJSON(json['type']),
    };
}

export function MenuItemToJSON(json: any): MenuItem {
    return MenuItemToJSONTyped(json, false);
}

export function MenuItemToJSONTyped(value?: MenuItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'price': value['price'],
        'id': value['id'],
        'type': MenuItemTypeToJSON(value['type']),
    };
}

