/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MenuBase
 */
export interface MenuBase {
    /**
     * 
     * @type {string}
     * @memberof MenuBase
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof MenuBase
     */
    price: number;
}

/**
 * Check if a given object implements the MenuBase interface.
 */
export function instanceOfMenuBase(value: object): value is MenuBase {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function MenuBaseFromJSON(json: any): MenuBase {
    return MenuBaseFromJSONTyped(json, false);
}

export function MenuBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuBase {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
    };
}

export function MenuBaseToJSON(json: any): MenuBase {
    return MenuBaseToJSONTyped(json, false);
}

export function MenuBaseToJSONTyped(value?: MenuBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'price': value['price'],
    };
}

