/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MenuUpdate
 */
export interface MenuUpdate {
    /**
     * 
     * @type {string}
     * @memberof MenuUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MenuUpdate
     */
    price?: number | null;
}

/**
 * Check if a given object implements the MenuUpdate interface.
 */
export function instanceOfMenuUpdate(value: object): value is MenuUpdate {
    return true;
}

export function MenuUpdateFromJSON(json: any): MenuUpdate {
    return MenuUpdateFromJSONTyped(json, false);
}

export function MenuUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function MenuUpdateToJSON(json: any): MenuUpdate {
    return MenuUpdateToJSONTyped(json, false);
}

export function MenuUpdateToJSONTyped(value?: MenuUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'price': value['price'],
    };
}

