/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MenuItemType = {
    Item: 'item',
    Modifier: 'modifier'
} as const;
export type MenuItemType = typeof MenuItemType[keyof typeof MenuItemType];


export function instanceOfMenuItemType(value: any): boolean {
    for (const key in MenuItemType) {
        if (Object.prototype.hasOwnProperty.call(MenuItemType, key)) {
            if (MenuItemType[key as keyof typeof MenuItemType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MenuItemTypeFromJSON(json: any): MenuItemType {
    return MenuItemTypeFromJSONTyped(json, false);
}

export function MenuItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuItemType {
    return json as MenuItemType;
}

export function MenuItemTypeToJSON(value?: MenuItemType | null): any {
    return value as any;
}

export function MenuItemTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MenuItemType {
    return value as MenuItemType;
}

