/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';
import type { OrderLineItemRead } from './OrderLineItemRead';
import {
    OrderLineItemReadFromJSON,
    OrderLineItemReadFromJSONTyped,
    OrderLineItemReadToJSON,
    OrderLineItemReadToJSONTyped,
} from './OrderLineItemRead';

/**
 * 
 * @export
 * @interface OrderWithLineItems
 */
export interface OrderWithLineItems {
    /**
     * 
     * @type {Order}
     * @memberof OrderWithLineItems
     */
    order: Order;
    /**
     * 
     * @type {Array<OrderLineItemRead>}
     * @memberof OrderWithLineItems
     */
    orderLineItems: Array<OrderLineItemRead>;
}

/**
 * Check if a given object implements the OrderWithLineItems interface.
 */
export function instanceOfOrderWithLineItems(value: object): value is OrderWithLineItems {
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('orderLineItems' in value) || value['orderLineItems'] === undefined) return false;
    return true;
}

export function OrderWithLineItemsFromJSON(json: any): OrderWithLineItems {
    return OrderWithLineItemsFromJSONTyped(json, false);
}

export function OrderWithLineItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderWithLineItems {
    if (json == null) {
        return json;
    }
    return {
        
        'order': OrderFromJSON(json['order']),
        'orderLineItems': ((json['order_line_items'] as Array<any>).map(OrderLineItemReadFromJSON)),
    };
}

export function OrderWithLineItemsToJSON(json: any): OrderWithLineItems {
    return OrderWithLineItemsToJSONTyped(json, false);
}

export function OrderWithLineItemsToJSONTyped(value?: OrderWithLineItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order': OrderToJSON(value['order']),
        'order_line_items': ((value['orderLineItems'] as Array<any>).map(OrderLineItemReadToJSON)),
    };
}

