/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MenuItem } from './MenuItem';
import {
    MenuItemFromJSON,
    MenuItemFromJSONTyped,
    MenuItemToJSON,
    MenuItemToJSONTyped,
} from './MenuItem';

/**
 * DTO for reading a line item, explicitly including its modifiers.
 * @export
 * @interface OrderLineItemRead
 */
export interface OrderLineItemRead {
    /**
     * 
     * @type {number}
     * @memberof OrderLineItemRead
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof OrderLineItemRead
     */
    orderId: number;
    /**
     * 
     * @type {number}
     * @memberof OrderLineItemRead
     */
    menuItemId: number;
    /**
     * 
     * @type {string}
     * @memberof OrderLineItemRead
     */
    itemName: string;
    /**
     * 
     * @type {number}
     * @memberof OrderLineItemRead
     */
    unitPrice: number;
    /**
     * 
     * @type {number}
     * @memberof OrderLineItemRead
     */
    quantity: number;
    /**
     * 
     * @type {Array<MenuItem>}
     * @memberof OrderLineItemRead
     */
    modifiers?: Array<MenuItem>;
}

/**
 * Check if a given object implements the OrderLineItemRead interface.
 */
export function instanceOfOrderLineItemRead(value: object): value is OrderLineItemRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('menuItemId' in value) || value['menuItemId'] === undefined) return false;
    if (!('itemName' in value) || value['itemName'] === undefined) return false;
    if (!('unitPrice' in value) || value['unitPrice'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function OrderLineItemReadFromJSON(json: any): OrderLineItemRead {
    return OrderLineItemReadFromJSONTyped(json, false);
}

export function OrderLineItemReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderLineItemRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orderId': json['order_id'],
        'menuItemId': json['menu_item_id'],
        'itemName': json['item_name'],
        'unitPrice': json['unit_price'],
        'quantity': json['quantity'],
        'modifiers': json['modifiers'] == null ? undefined : ((json['modifiers'] as Array<any>).map(MenuItemFromJSON)),
    };
}

export function OrderLineItemReadToJSON(json: any): OrderLineItemRead {
    return OrderLineItemReadToJSONTyped(json, false);
}

export function OrderLineItemReadToJSONTyped(value?: OrderLineItemRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'order_id': value['orderId'],
        'menu_item_id': value['menuItemId'],
        'item_name': value['itemName'],
        'unit_price': value['unitPrice'],
        'quantity': value['quantity'],
        'modifiers': value['modifiers'] == null ? undefined : ((value['modifiers'] as Array<any>).map(MenuItemToJSON)),
    };
}

