/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';

/**
 * 
 * @export
 * @interface UserRead
 */
export interface UserRead {
    /**
     * 
     * @type {string}
     * @memberof UserRead
     */
    name: string;
    /**
     * 
     * @type {Role}
     * @memberof UserRead
     */
    role: Role;
    /**
     * 
     * @type {number}
     * @memberof UserRead
     */
    id: number;
}



/**
 * Check if a given object implements the UserRead interface.
 */
export function instanceOfUserRead(value: object): value is UserRead {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserReadFromJSON(json: any): UserRead {
    return UserReadFromJSONTyped(json, false);
}

export function UserReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRead {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'role': RoleFromJSON(json['role']),
        'id': json['id'],
    };
}

export function UserReadToJSON(json: any): UserRead {
    return UserReadToJSONTyped(json, false);
}

export function UserReadToJSONTyped(value?: UserRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'role': RoleToJSON(value['role']),
        'id': value['id'],
    };
}

