"""add notes to orderitemlist

Revision ID: 235b6af42d2b
Revises: 
Create Date: 2026-04-12 16:17:39.503709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235b6af42d2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('table')
    op.drop_table('orderlineitemmodifierlink')
    op.drop_table('menuitem')
    op.drop_table('orderlineitem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderlineitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menuitem.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menuitem',
    sa.Column('name', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderlineitemmodifierlink',
    sa.Column('line_item_id', sa.INTEGER(), nullable=False),
    sa.Column('modifier_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['orderlineitem.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['menuitem.id'], ),
    sa.PrimaryKeyConstraint('line_item_id', 'modifier_id')
    )
    op.create_table('table',
    sa.Column('table_name', sa.VARCHAR(), nullable=False),
    sa.Column('capacity', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
