"""update user model

Revision ID: 7e699a0f25cb
Revises: 
Create Date: 2026-04-04 16:31:31.202219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e699a0f25cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero')
    op.add_column('user', sa.Column('role', sa.Enum('WAITER', 'COOK', 'MANAGER', name='role'), nullable=False))
    op.drop_column('user', 'age')
    op.drop_column('user', 'secret_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('secret_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'role')
    op.create_table('hero',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('secret_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
