"""add password_hash to user

Revision ID: cf47956736ae
Revises: 235b6af42d2b
Create Date: 2026-04-14 15:43:25.908584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf47956736ae'
down_revision: Union[str, Sequence[str], None] = '235b6af42d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="temp_hash"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.create_table('orderlineitem',
    sa.Column('id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('order_id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('item_name', sa.VARCHAR(), nullable=False, server_default="temp_hash"),
    sa.Column('unit_price', sa.FLOAT(), nullable=False, server_default="temp_hash"),
    sa.Column('quantity', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menuitem.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('table_name', sa.VARCHAR(), nullable=False, server_default="temp_hash"),
    sa.Column('capacity', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False, server_default="temp_hash"),
    sa.Column('id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('table_id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('user_id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False, server_default="temp_hash"),
    sa.Column('created_at', sa.DATETIME(), nullable=False, server_default="temp_hash"),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderlineitemmodifierlink',
    sa.Column('line_item_id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('modifier_id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.ForeignKeyConstraint(['line_item_id'], ['orderlineitem.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['menuitem.id'], ),
    sa.PrimaryKeyConstraint('line_item_id', 'modifier_id')
    )
    op.create_table('menuitem',
    sa.Column('name', sa.VARCHAR(length=1000), nullable=False, server_default="temp_hash"),
    sa.Column('price', sa.FLOAT(), nullable=False, server_default="temp_hash"),
    sa.Column('id', sa.INTEGER(), nullable=False, server_default="temp_hash"),
    sa.Column('type', sa.VARCHAR(length=8), nullable=False, server_default="temp_hash"),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
