/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MenuBase,
  MenuItem,
  MenuUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MenuBaseFromJSON,
    MenuBaseToJSON,
    MenuItemFromJSON,
    MenuItemToJSON,
    MenuUpdateFromJSON,
    MenuUpdateToJSON,
} from '../models/index';

export interface CreateMenuItemMenuItemPostRequest {
    menuBase: MenuBase;
}

export interface CreateModifierMenuModifierPostRequest {
    menuBase: MenuBase;
}

export interface DeleteMenuItemMenuItemMenuItemIdDeleteRequest {
    menuItemId: number;
}

export interface DeleteModifierMenuModifierModifierIdDeleteRequest {
    modifierId: number;
}

export interface ListModifiersMenuModifierGetRequest {
    offset?: number;
    limit?: number | null;
}

export interface ListTablesMenuItemGetRequest {
    offset?: number;
    limit?: number | null;
}

export interface PartialUpdateItemMenuItemMenuItemIdPatchRequest {
    menuItemId: number;
    menuUpdate: MenuUpdate;
}

export interface PartialUpdateModifierMenuModifierModifierIdPatchRequest {
    modifierId: number;
    menuUpdate: MenuUpdate;
}

export interface RetrieveMenuItemMenuItemMenuItemIdGetRequest {
    menuItemId: number;
}

export interface RetrieveModifierMenuModifierModifierIdGetRequest {
    modifierId: number;
}

/**
 * 
 */
export class MenuApi extends runtime.BaseAPI {

    /**
     * Creates request options for createMenuItemMenuItemPost without sending the request
     */
    async createMenuItemMenuItemPostRequestOpts(requestParameters: CreateMenuItemMenuItemPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['menuBase'] == null) {
            throw new runtime.RequiredError(
                'menuBase',
                'Required parameter "menuBase" was null or undefined when calling createMenuItemMenuItemPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/item/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MenuBaseToJSON(requestParameters['menuBase']),
        };
    }

    /**
     * Create a new menu item.
     * Create Menu Item
     */
    async createMenuItemMenuItemPostRaw(requestParameters: CreateMenuItemMenuItemPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MenuItem>> {
        const requestOptions = await this.createMenuItemMenuItemPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MenuItemFromJSON(jsonValue));
    }

    /**
     * Create a new menu item.
     * Create Menu Item
     */
    async createMenuItemMenuItemPost(requestParameters: CreateMenuItemMenuItemPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MenuItem> {
        const response = await this.createMenuItemMenuItemPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createModifierMenuModifierPost without sending the request
     */
    async createModifierMenuModifierPostRequestOpts(requestParameters: CreateModifierMenuModifierPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['menuBase'] == null) {
            throw new runtime.RequiredError(
                'menuBase',
                'Required parameter "menuBase" was null or undefined when calling createModifierMenuModifierPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/modifier/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MenuBaseToJSON(requestParameters['menuBase']),
        };
    }

    /**
     * Create a new menu modifier.
     * Create Modifier
     */
    async createModifierMenuModifierPostRaw(requestParameters: CreateModifierMenuModifierPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MenuItem>> {
        const requestOptions = await this.createModifierMenuModifierPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MenuItemFromJSON(jsonValue));
    }

    /**
     * Create a new menu modifier.
     * Create Modifier
     */
    async createModifierMenuModifierPost(requestParameters: CreateModifierMenuModifierPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MenuItem> {
        const response = await this.createModifierMenuModifierPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteMenuItemMenuItemMenuItemIdDelete without sending the request
     */
    async deleteMenuItemMenuItemMenuItemIdDeleteRequestOpts(requestParameters: DeleteMenuItemMenuItemMenuItemIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['menuItemId'] == null) {
            throw new runtime.RequiredError(
                'menuItemId',
                'Required parameter "menuItemId" was null or undefined when calling deleteMenuItemMenuItemMenuItemIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/item/{menu_item_id}`;
        urlPath = urlPath.replace(`{${"menu_item_id"}}`, encodeURIComponent(String(requestParameters['menuItemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a menu item by ID.
     * Delete Menu Item
     */
    async deleteMenuItemMenuItemMenuItemIdDeleteRaw(requestParameters: DeleteMenuItemMenuItemMenuItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteMenuItemMenuItemMenuItemIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a menu item by ID.
     * Delete Menu Item
     */
    async deleteMenuItemMenuItemMenuItemIdDelete(requestParameters: DeleteMenuItemMenuItemMenuItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMenuItemMenuItemMenuItemIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteModifierMenuModifierModifierIdDelete without sending the request
     */
    async deleteModifierMenuModifierModifierIdDeleteRequestOpts(requestParameters: DeleteModifierMenuModifierModifierIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modifierId'] == null) {
            throw new runtime.RequiredError(
                'modifierId',
                'Required parameter "modifierId" was null or undefined when calling deleteModifierMenuModifierModifierIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/modifier/{modifier_id}`;
        urlPath = urlPath.replace(`{${"modifier_id"}}`, encodeURIComponent(String(requestParameters['modifierId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a menu modifier by ID.
     * Delete Modifier
     */
    async deleteModifierMenuModifierModifierIdDeleteRaw(requestParameters: DeleteModifierMenuModifierModifierIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteModifierMenuModifierModifierIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a menu modifier by ID.
     * Delete Modifier
     */
    async deleteModifierMenuModifierModifierIdDelete(requestParameters: DeleteModifierMenuModifierModifierIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteModifierMenuModifierModifierIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listModifiersMenuModifierGet without sending the request
     */
    async listModifiersMenuModifierGetRequestOpts(requestParameters: ListModifiersMenuModifierGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/modifier/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all menu modifiers with pagination.
     * List Modifiers
     */
    async listModifiersMenuModifierGetRaw(requestParameters: ListModifiersMenuModifierGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MenuItem>>> {
        const requestOptions = await this.listModifiersMenuModifierGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MenuItemFromJSON));
    }

    /**
     * Get all menu modifiers with pagination.
     * List Modifiers
     */
    async listModifiersMenuModifierGet(requestParameters: ListModifiersMenuModifierGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MenuItem>> {
        const response = await this.listModifiersMenuModifierGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTablesMenuItemGet without sending the request
     */
    async listTablesMenuItemGetRequestOpts(requestParameters: ListTablesMenuItemGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/item/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all menu items with pagination.
     * List Tables
     */
    async listTablesMenuItemGetRaw(requestParameters: ListTablesMenuItemGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MenuItem>>> {
        const requestOptions = await this.listTablesMenuItemGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MenuItemFromJSON));
    }

    /**
     * Get all menu items with pagination.
     * List Tables
     */
    async listTablesMenuItemGet(requestParameters: ListTablesMenuItemGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MenuItem>> {
        const response = await this.listTablesMenuItemGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateItemMenuItemMenuItemIdPatch without sending the request
     */
    async partialUpdateItemMenuItemMenuItemIdPatchRequestOpts(requestParameters: PartialUpdateItemMenuItemMenuItemIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['menuItemId'] == null) {
            throw new runtime.RequiredError(
                'menuItemId',
                'Required parameter "menuItemId" was null or undefined when calling partialUpdateItemMenuItemMenuItemIdPatch().'
            );
        }

        if (requestParameters['menuUpdate'] == null) {
            throw new runtime.RequiredError(
                'menuUpdate',
                'Required parameter "menuUpdate" was null or undefined when calling partialUpdateItemMenuItemMenuItemIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/item/{menu_item_id}`;
        urlPath = urlPath.replace(`{${"menu_item_id"}}`, encodeURIComponent(String(requestParameters['menuItemId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MenuUpdateToJSON(requestParameters['menuUpdate']),
        };
    }

    /**
     * Partially update a menu item (only provided fields).
     * Partial Update Item
     */
    async partialUpdateItemMenuItemMenuItemIdPatchRaw(requestParameters: PartialUpdateItemMenuItemMenuItemIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MenuItem>> {
        const requestOptions = await this.partialUpdateItemMenuItemMenuItemIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MenuItemFromJSON(jsonValue));
    }

    /**
     * Partially update a menu item (only provided fields).
     * Partial Update Item
     */
    async partialUpdateItemMenuItemMenuItemIdPatch(requestParameters: PartialUpdateItemMenuItemMenuItemIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MenuItem> {
        const response = await this.partialUpdateItemMenuItemMenuItemIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateModifierMenuModifierModifierIdPatch without sending the request
     */
    async partialUpdateModifierMenuModifierModifierIdPatchRequestOpts(requestParameters: PartialUpdateModifierMenuModifierModifierIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modifierId'] == null) {
            throw new runtime.RequiredError(
                'modifierId',
                'Required parameter "modifierId" was null or undefined when calling partialUpdateModifierMenuModifierModifierIdPatch().'
            );
        }

        if (requestParameters['menuUpdate'] == null) {
            throw new runtime.RequiredError(
                'menuUpdate',
                'Required parameter "menuUpdate" was null or undefined when calling partialUpdateModifierMenuModifierModifierIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/modifier/{modifier_id}`;
        urlPath = urlPath.replace(`{${"modifier_id"}}`, encodeURIComponent(String(requestParameters['modifierId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MenuUpdateToJSON(requestParameters['menuUpdate']),
        };
    }

    /**
     * Partially update a menu modifier (only provided fields).
     * Partial Update Modifier
     */
    async partialUpdateModifierMenuModifierModifierIdPatchRaw(requestParameters: PartialUpdateModifierMenuModifierModifierIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MenuItem>> {
        const requestOptions = await this.partialUpdateModifierMenuModifierModifierIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MenuItemFromJSON(jsonValue));
    }

    /**
     * Partially update a menu modifier (only provided fields).
     * Partial Update Modifier
     */
    async partialUpdateModifierMenuModifierModifierIdPatch(requestParameters: PartialUpdateModifierMenuModifierModifierIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MenuItem> {
        const response = await this.partialUpdateModifierMenuModifierModifierIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retrieveMenuItemMenuItemMenuItemIdGet without sending the request
     */
    async retrieveMenuItemMenuItemMenuItemIdGetRequestOpts(requestParameters: RetrieveMenuItemMenuItemMenuItemIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['menuItemId'] == null) {
            throw new runtime.RequiredError(
                'menuItemId',
                'Required parameter "menuItemId" was null or undefined when calling retrieveMenuItemMenuItemMenuItemIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/item/{menu_item_id}`;
        urlPath = urlPath.replace(`{${"menu_item_id"}}`, encodeURIComponent(String(requestParameters['menuItemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single menu item by ID.
     * Retrieve Menu Item
     */
    async retrieveMenuItemMenuItemMenuItemIdGetRaw(requestParameters: RetrieveMenuItemMenuItemMenuItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MenuItem>> {
        const requestOptions = await this.retrieveMenuItemMenuItemMenuItemIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MenuItemFromJSON(jsonValue));
    }

    /**
     * Get a single menu item by ID.
     * Retrieve Menu Item
     */
    async retrieveMenuItemMenuItemMenuItemIdGet(requestParameters: RetrieveMenuItemMenuItemMenuItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MenuItem> {
        const response = await this.retrieveMenuItemMenuItemMenuItemIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retrieveModifierMenuModifierModifierIdGet without sending the request
     */
    async retrieveModifierMenuModifierModifierIdGetRequestOpts(requestParameters: RetrieveModifierMenuModifierModifierIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modifierId'] == null) {
            throw new runtime.RequiredError(
                'modifierId',
                'Required parameter "modifierId" was null or undefined when calling retrieveModifierMenuModifierModifierIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/menu/modifier/{modifier_id}`;
        urlPath = urlPath.replace(`{${"modifier_id"}}`, encodeURIComponent(String(requestParameters['modifierId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single menu modifier by ID.
     * Retrieve Modifier
     */
    async retrieveModifierMenuModifierModifierIdGetRaw(requestParameters: RetrieveModifierMenuModifierModifierIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MenuItem>> {
        const requestOptions = await this.retrieveModifierMenuModifierModifierIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MenuItemFromJSON(jsonValue));
    }

    /**
     * Get a single menu modifier by ID.
     * Retrieve Modifier
     */
    async retrieveModifierMenuModifierModifierIdGet(requestParameters: RetrieveModifierMenuModifierModifierIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MenuItem> {
        const response = await this.retrieveModifierMenuModifierModifierIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
