/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyCreateOrderOrderPost,
  HTTPValidationError,
  Order,
  OrderStatus,
  OrderUpdate,
  OrderWithLineItems,
} from '../models/index';
import {
    BodyCreateOrderOrderPostFromJSON,
    BodyCreateOrderOrderPostToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    OrderFromJSON,
    OrderToJSON,
    OrderStatusFromJSON,
    OrderStatusToJSON,
    OrderUpdateFromJSON,
    OrderUpdateToJSON,
    OrderWithLineItemsFromJSON,
    OrderWithLineItemsToJSON,
} from '../models/index';

export interface CreateOrderOrderPostRequest {
    bodyCreateOrderOrderPost: BodyCreateOrderOrderPost;
}

export interface DeleteOrderOrderOrderIdDeleteRequest {
    orderId: number;
}

export interface ListOrdersOrderGetRequest {
    offset?: number;
    limit?: number;
    status?: OrderStatus | null;
    tableId?: number | null;
    userId?: number | null;
}

export interface PartialUpdateOrderOrderOrderIdPatchRequest {
    orderId: number;
    orderUpdate: OrderUpdate;
}

export interface RetrieveOrderOrderOrderIdGetRequest {
    orderId: number;
}

/**
 * 
 */
export class OrderApi extends runtime.BaseAPI {

    /**
     * Creates request options for createOrderOrderPost without sending the request
     */
    async createOrderOrderPostRequestOpts(requestParameters: CreateOrderOrderPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bodyCreateOrderOrderPost'] == null) {
            throw new runtime.RequiredError(
                'bodyCreateOrderOrderPost',
                'Required parameter "bodyCreateOrderOrderPost" was null or undefined when calling createOrderOrderPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/order/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyCreateOrderOrderPostToJSON(requestParameters['bodyCreateOrderOrderPost']),
        };
    }

    /**
     * Create a new order.
     * Create Order
     */
    async createOrderOrderPostRaw(requestParameters: CreateOrderOrderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        const requestOptions = await this.createOrderOrderPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Create a new order.
     * Create Order
     */
    async createOrderOrderPost(requestParameters: CreateOrderOrderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.createOrderOrderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteOrderOrderOrderIdDelete without sending the request
     */
    async deleteOrderOrderOrderIdDeleteRequestOpts(requestParameters: DeleteOrderOrderOrderIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling deleteOrderOrderOrderIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/order/{order_id}`;
        urlPath = urlPath.replace(`{${"order_id"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an order by ID.
     * Delete Order
     */
    async deleteOrderOrderOrderIdDeleteRaw(requestParameters: DeleteOrderOrderOrderIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteOrderOrderOrderIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an order by ID.
     * Delete Order
     */
    async deleteOrderOrderOrderIdDelete(requestParameters: DeleteOrderOrderOrderIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrderOrderOrderIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listOrdersOrderGet without sending the request
     */
    async listOrdersOrderGetRequestOpts(requestParameters: ListOrdersOrderGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['tableId'] != null) {
            queryParameters['table_id'] = requestParameters['tableId'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/order/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Orders
     */
    async listOrdersOrderGetRaw(requestParameters: ListOrdersOrderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderWithLineItems>>> {
        const requestOptions = await this.listOrdersOrderGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderWithLineItemsFromJSON));
    }

    /**
     * List Orders
     */
    async listOrdersOrderGet(requestParameters: ListOrdersOrderGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderWithLineItems>> {
        const response = await this.listOrdersOrderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateOrderOrderOrderIdPatch without sending the request
     */
    async partialUpdateOrderOrderOrderIdPatchRequestOpts(requestParameters: PartialUpdateOrderOrderOrderIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling partialUpdateOrderOrderOrderIdPatch().'
            );
        }

        if (requestParameters['orderUpdate'] == null) {
            throw new runtime.RequiredError(
                'orderUpdate',
                'Required parameter "orderUpdate" was null or undefined when calling partialUpdateOrderOrderOrderIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/order/{order_id}`;
        urlPath = urlPath.replace(`{${"order_id"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: OrderUpdateToJSON(requestParameters['orderUpdate']),
        };
    }

    /**
     * Partially update an order (only provided fields).
     * Partial Update Order
     */
    async partialUpdateOrderOrderOrderIdPatchRaw(requestParameters: PartialUpdateOrderOrderOrderIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        const requestOptions = await this.partialUpdateOrderOrderOrderIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Partially update an order (only provided fields).
     * Partial Update Order
     */
    async partialUpdateOrderOrderOrderIdPatch(requestParameters: PartialUpdateOrderOrderOrderIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.partialUpdateOrderOrderOrderIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retrieveOrderOrderOrderIdGet without sending the request
     */
    async retrieveOrderOrderOrderIdGetRequestOpts(requestParameters: RetrieveOrderOrderOrderIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling retrieveOrderOrderOrderIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/order/{order_id}`;
        urlPath = urlPath.replace(`{${"order_id"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single order by ID.
     * Retrieve Order
     */
    async retrieveOrderOrderOrderIdGetRaw(requestParameters: RetrieveOrderOrderOrderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        const requestOptions = await this.retrieveOrderOrderOrderIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Get a single order by ID.
     * Retrieve Order
     */
    async retrieveOrderOrderOrderIdGet(requestParameters: RetrieveOrderOrderOrderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.retrieveOrderOrderOrderIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
