/* tslint:disable */
/* eslint-disable */
/**
 * Restaurant POS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Table,
  TableBase,
  TableUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    TableFromJSON,
    TableToJSON,
    TableBaseFromJSON,
    TableBaseToJSON,
    TableUpdateFromJSON,
    TableUpdateToJSON,
} from '../models/index';

export interface CreateTableTablePostRequest {
    tableBase: TableBase;
}

export interface DeleteTableTableTableIdDeleteRequest {
    tableId: number;
}

export interface ListTablesTableGetRequest {
    offset?: number;
    limit?: number;
}

export interface PartialUpdateTableTableTableIdPatchRequest {
    tableId: number;
    tableUpdate: TableUpdate;
}

export interface RetrieveTableTableTableIdGetRequest {
    tableId: number;
}

/**
 * 
 */
export class TableApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTableTablePost without sending the request
     */
    async createTableTablePostRequestOpts(requestParameters: CreateTableTablePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tableBase'] == null) {
            throw new runtime.RequiredError(
                'tableBase',
                'Required parameter "tableBase" was null or undefined when calling createTableTablePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/table/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TableBaseToJSON(requestParameters['tableBase']),
        };
    }

    /**
     * Create a new table.
     * Create Table
     */
    async createTableTablePostRaw(requestParameters: CreateTableTablePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Table>> {
        const requestOptions = await this.createTableTablePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TableFromJSON(jsonValue));
    }

    /**
     * Create a new table.
     * Create Table
     */
    async createTableTablePost(requestParameters: CreateTableTablePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Table> {
        const response = await this.createTableTablePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTableTableTableIdDelete without sending the request
     */
    async deleteTableTableTableIdDeleteRequestOpts(requestParameters: DeleteTableTableTableIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tableId'] == null) {
            throw new runtime.RequiredError(
                'tableId',
                'Required parameter "tableId" was null or undefined when calling deleteTableTableTableIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/table/{table_id}`;
        urlPath = urlPath.replace(`{${"table_id"}}`, encodeURIComponent(String(requestParameters['tableId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a table by ID.
     * Delete Table
     */
    async deleteTableTableTableIdDeleteRaw(requestParameters: DeleteTableTableTableIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTableTableTableIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a table by ID.
     * Delete Table
     */
    async deleteTableTableTableIdDelete(requestParameters: DeleteTableTableTableIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTableTableTableIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listTablesTableGet without sending the request
     */
    async listTablesTableGetRequestOpts(requestParameters: ListTablesTableGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/table/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all tables with pagination.
     * List Tables
     */
    async listTablesTableGetRaw(requestParameters: ListTablesTableGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Table>>> {
        const requestOptions = await this.listTablesTableGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TableFromJSON));
    }

    /**
     * Get all tables with pagination.
     * List Tables
     */
    async listTablesTableGet(requestParameters: ListTablesTableGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Table>> {
        const response = await this.listTablesTableGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateTableTableTableIdPatch without sending the request
     */
    async partialUpdateTableTableTableIdPatchRequestOpts(requestParameters: PartialUpdateTableTableTableIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tableId'] == null) {
            throw new runtime.RequiredError(
                'tableId',
                'Required parameter "tableId" was null or undefined when calling partialUpdateTableTableTableIdPatch().'
            );
        }

        if (requestParameters['tableUpdate'] == null) {
            throw new runtime.RequiredError(
                'tableUpdate',
                'Required parameter "tableUpdate" was null or undefined when calling partialUpdateTableTableTableIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/table/{table_id}`;
        urlPath = urlPath.replace(`{${"table_id"}}`, encodeURIComponent(String(requestParameters['tableId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TableUpdateToJSON(requestParameters['tableUpdate']),
        };
    }

    /**
     * Partially update a table (only provided fields).
     * Partial Update Table
     */
    async partialUpdateTableTableTableIdPatchRaw(requestParameters: PartialUpdateTableTableTableIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Table>> {
        const requestOptions = await this.partialUpdateTableTableTableIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TableFromJSON(jsonValue));
    }

    /**
     * Partially update a table (only provided fields).
     * Partial Update Table
     */
    async partialUpdateTableTableTableIdPatch(requestParameters: PartialUpdateTableTableTableIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Table> {
        const response = await this.partialUpdateTableTableTableIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retrieveTableTableTableIdGet without sending the request
     */
    async retrieveTableTableTableIdGetRequestOpts(requestParameters: RetrieveTableTableTableIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tableId'] == null) {
            throw new runtime.RequiredError(
                'tableId',
                'Required parameter "tableId" was null or undefined when calling retrieveTableTableTableIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/table/{table_id}`;
        urlPath = urlPath.replace(`{${"table_id"}}`, encodeURIComponent(String(requestParameters['tableId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single table by ID.
     * Retrieve Table
     */
    async retrieveTableTableTableIdGetRaw(requestParameters: RetrieveTableTableTableIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Table>> {
        const requestOptions = await this.retrieveTableTableTableIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TableFromJSON(jsonValue));
    }

    /**
     * Get a single table by ID.
     * Retrieve Table
     */
    async retrieveTableTableTableIdGet(requestParameters: RetrieveTableTableTableIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Table> {
        const response = await this.retrieveTableTableTableIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
